In [1]:
pip install tweepy

Collecting tweepy
  Obtaining dependency information for tweepy from https://files.pythonhosted.org/packages/4d/78/ba0065d5636bbf4a35b78c4f81b74e7858b609cdf69e629d6da5c91b9d92/tweepy-4.14.0-py3-none-any.whl.metadata
  Downloading tweepy-4.14.0-py3-none-any.whl.metadata (3.8 kB)
Collecting oauthlib<4,>=3.2.0 (from tweepy)
  Obtaining dependency information for oauthlib<4,>=3.2.0 from https://files.pythonhosted.org/packages/7e/80/cab10959dc1faead58dc8384a781dfbf93cb4d33d50988f7a69f1b7c9bbe/oauthlib-3.2.2-py3-none-any.whl.metadata
  Downloading oauthlib-3.2.2-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: requests<3,>=2.27.0 in /Users/mac/anaconda3/lib/python3.11/site-packages (from tweepy) (2.32.3)
Collecting requests-oauthlib<2,>=1.2.0 (from tweepy)
  Obtaining dependency information for requests-oauthlib<2,>=1.2.0 from https://files.pythonhosted.org/packages/6f/bb/5deac77a9af870143c684ab46a7934038a53eb4aa975bc0687ed6ca2c610/requests_oauthlib-1.3.1-py2.py3-none-any.whl.metadata
  Downloading requests_oauthlib-1.3.1-py2.py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/mac/anaconda3/lib/python3.11/site-packages (from requests<3,>=2.27.0->tweepy) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/mac/anaconda3/lib/python3.11/site-packages (from requests<3,>=2.27.0->tweepy) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/mac/anaconda3/lib/python3.11/site-packages (from requests<3,>=2.27.0->tweepy) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /Users/mac/anaconda3/lib/python3.11/site-packages (from requests<3,>=2.27.0->tweepy) (2024.7.4)
Downloading tweepy-4.14.0-py3-none-any.whl (98 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.5/98.5 kB 470.3 kB/s eta 0:00:00a 0:00:01
Downloading oauthlib-3.2.2-py3-none-any.whl (151 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 151.7/151.7 kB 1.0 MB/s eta 0:00:00a 0:00:01
Downloading requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Installing collected packages: oauthlib, requests-oauthlib, tweepy
Successfully installed oauthlib-3.2.2 requests-oauthlib-1.3.1 tweepy-4.14.0
Note: you may need to restart the kernel to use updated packages.

In [2]:
#Api-Key
#LnE70nTWLBj8gNzsZLqTg0fc2

In [3]:
#Key Secret
#FQNce84atuSGWbX3iToGZehVs16khgc4lQuXKjHnomU7pC1cNo

#Access Token
#1449605225627766785-G1MtfkAlFMkfWqGn9UNkuDDBhbKbjh
#Access Token Secret
#TyNGAe8UIFuxDto0sYb1MafFdBnE9VTDO0uXOoYn7HAkk

In [4]:
import tweepy


API_KEY = 'LnE70nTWLBj8gNzsZLqTg0fc2'
API_SECRET_KEY = 'FQNce84atuSGWbX3iToGZehVs16khgc4lQuXKjHnomU7pC1cNo'
ACCESS_TOKEN = '1449605225627766785-G1MtfkAlFMkfWqGn9UNkuDDBhbKbjh'
ACCESS_TOKEN_SECRET = 'TyNGAe8UIFuxDto0sYb1MafFdBnE9VTDO0uXOoYn7HAkk'

# Authenticate
auth = tweepy.OAuthHandler(API_KEY, API_SECRET_KEY)
auth.set_access_token(ACCESS_TOKEN, ACCESS_TOKEN_SECRET)
api = tweepy.API(auth)

# Fetch tweets
query = "COVID-19 OR coronavirus OR pandemic -filter:retweets"
tweets = tweepy.Cursor(api.search_tweets, q=query, lang="en", tweet_mode='extended').items(100)

# Extract text
tweet_list = [tweet.full_text for tweet in tweets]
print(tweet_list[:5])

Forbidden: 403 Forbidden
453 - You currently have access to a subset of X API V2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.x.com/en/portal/product

In [5]:
#Bearer_token
#AAAAAAAAAAAAAAAAAAAAAIOLxQEAAAAA6GgU8VyhbN6xVpYtkzCr5FCHA00%3DOW09j23hnMR4UHc6zpnbtUJLcPQ9piUSXR97Bp5zzuFMDn31Tk

In [6]:
import requests

# Bearer Token
BEARER_TOKEN = "AAAAAAAAAAAAAAAAAAAAAIOLxQEAAAAA6GgU8VyhbN6xVpYtkzCr5FCHA00%3DOW09j23hnMR4UHc6zpnbtUJLcPQ9piUSXR97Bp5zzuFMDn31Tk"

# Endpoint and Query
url = "https://api.twitter.com/2/tweets/search/recent"
query_params = {
    'query': 'covid19',  # Replace with your desired query
    'max_results': 10
}

# Headers
headers = {
    "Authorization": f"Bearer {BEARER_TOKEN}"
}

# API Request
response = requests.get(url, headers=headers, params=query_params)

if response.status_code == 200:
    tweets = response.json()
    for tweet in tweets.get('data', []):
        print(tweet['text'])
else:
    print(f"Error: {response.status_code}, {response.text}")

#COVID19 #ID2020 #pandemia #GreatReset #Transhumanismo #Espana #España #CampoDeConcentraciónGlobal #Auschwitz #Agenda2030 #OMS #BillGates
@davidicke

@DraPatriciaDeNa

@ainhoabilboa

@JuezLopezMDP

@JulioRazona

@veronicaressia

@leogbayona

@Xar_Crystal

@ulises37

@tatious_… https://t.co/by8DrWOFaf https://t.co/LU4PUCcqKf
RT @Excelsior: 🚨☣️ México registró 683 decesos y 14 mil 017 casos confirmados de #Covid19, hasta el pasado 30 de noviembre.

https://t.co/E…
RT @MSGAllTrading: MSG 9 bar 9 Hair oil is rich in vitamin B-7, or biotin, which helps to keep hair strong &amp; healthy. It can also help prot…
RT @Sanjay_Dixit: JNU scientists including @ARanganathan72 make big discovery that could change malaria Covid19 treatment https://t.co/CeYP…
RT @Sanjay_Dixit: JNU scientists including @ARanganathan72 make big discovery that could change malaria Covid19 treatment https://t.co/CeYP…
RT @lorenabeauregar: @Arouet_V @revistaetcetera Estos casos ameritan renuncias. Pero no van a ocurrir; recordemos: nadie fue sacrificado en…
RT @AvoBrazOrunMa4: @MrMugsy2U #authoritarians like #trump don’t even like their own supporters.
#MAGAs are being used. #trump said that #…
RT @MSGAllTrading: MSG Immu Boost helps in boosting immunity. In addition, it is beneficial in recurrent disease conditions such as cold, c…
@COVID19_disease https://t.co/23eNzASAHS
RT @MSGAllTrading: MSG7-7 Shampoo Intense Repair Shampoo improves your hair health. It offers unbeatable damage control and nourishes and e…

In [7]:
import pandas as pd

In [9]:
data= pd.read_csv('biweekly_cases_per_million.csv')
data.tail()

,date,World,Afghanistan,Africa,Albania,Algeria,American Samoa,Andorra,Angola,Anguilla,...,Uruguay,Uzbekistan,Vanuatu,Vatican,Venezuela,Vietnam,Wallis and Futuna,Yemen,Zambia,Zimbabwe
1669,2024-07-31,13.530,0.0,0.191,0.0,0.836,0.0,0.0,0.0,0.0,...,7.078,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.722,0.062
1670,2024-08-01,13.530,0.0,0.191,0.0,0.836,0.0,0.0,0.0,0.0,...,7.078,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.722,0.062
1671,2024-08-02,13.530,0.0,0.191,0.0,0.836,0.0,0.0,0.0,0.0,...,7.078,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.722,0.062
1672,2024-08-03,13.530,0.0,0.191,0.0,0.836,0.0,0.0,0.0,0.0,...,7.078,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.722,0.062
1673,2024-08-04,12.915,0.0,0.118,0.0,0.528,0.0,0.0,0.0,0.0,...,7.962,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.622,0.000

In [11]:
data

,date,World,Afghanistan,Africa,Albania,Algeria,American Samoa,Andorra,Angola,Anguilla,...,Uruguay,Uzbekistan,Vanuatu,Vatican,Venezuela,Vietnam,Wallis and Futuna,Yemen,Zambia,Zimbabwe
0,2020-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-01-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1669,2024-07-31,13.530,0.0,0.191,0.0,0.836,0.0,0.0,0.0,0.0,...,7.078,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.722,0.062
1670,2024-08-01,13.530,0.0,0.191,0.0,0.836,0.0,0.0,0.0,0.0,...,7.078,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.722,0.062
1671,2024-08-02,13.530,0.0,0.191,0.0,0.836,0.0,0.0,0.0,0.0,...,7.078,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.722,0.062
1672,2024-08-03,13.530,0.0,0.191,0.0,0.836,0.0,0.0,0.0,0.0,...,7.078,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.722,0.062
1673,2024-08-04,12.915,0.0,0.118,0.0,0.528,0.0,0.0,0.0,0.0,...,7.962,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.622,0.000

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1674 entries, 0 to 1673
Columns: 247 entries, date to Zimbabwe
dtypes: float64(246), object(1)
memory usage: 3.2+ MB

In [16]:
data.describe()

,World,Afghanistan,Africa,Albania,Algeria,American Samoa,Andorra,Angola,Anguilla,Antigua and Barbuda,...,Uruguay,Uzbekistan,Vanuatu,Vatican,Venezuela,Vietnam,Wallis and Futuna,Yemen,Zambia,Zimbabwe
count,1662.000000,1662.000000,1662.000000,1662.000000,1662.000000,1662.000000,1662.000000,1662.000000,1662.000000,1662.000000,...,1662.000000,1662.000000,1662.000000,1662.000000,1662.000000,1662.000000,1662.000000,1662.000000,1662.000000,1661.000000
mean,818.047384,48.827072,76.568851,998.119361,50.403632,1455.861777,5073.360968,25.406900,2315.566811,826.110416,...,2586.827515,42.211045,323.396273,426.926403,165.018640,982.294526,2753.906992,2.632421,146.211217,139.726132
std,1195.812974,89.904923,104.999984,1679.220074,87.882378,6897.765257,10981.534497,57.312977,4984.787379,2081.474395,...,6402.273709,86.707158,1300.455621,2727.669507,226.484057,3957.877380,21323.532677,5.826896,354.453972,392.412685
min,0.006000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,65.095250,10.824250,2.266500,15.207500,0.418000,0.000000,0.000000,0.540000,0.000000,0.000000,...,11.648500,0.000000,0.000000,0.000000,0.000000,0.201000,0.000000,0.000000,1.340000,2.925000
50%,603.800000,18.138000,27.224000,95.487000,3.188000,0.000000,1191.641000,5.192000,0.000000,21.540000,...,326.461000,5.839000,0.000000,0.000000,30.908000,3.792000,0.000000,0.078000,27.788000,18.358000
75%,1021.380000,48.892000,109.142000,1416.742000,63.394000,41.352000,6171.446000,24.779000,2041.966000,506.187000,...,2008.898000,24.471000,0.000000,0.000000,252.508000,200.340000,0.000000,1.988000,97.207000,81.212000
max,9008.222000,600.288000,436.153000,9724.096000,523.909000,67383.440000,83000.930000,494.822000,28869.174000,13322.420000,...,45416.973000,483.300000,10125.790000,27290.450000,964.626000,35346.355000,230762.550000,37.124000,2480.780000,3307.598000